### PR TITLE
[Suggetion] Updating READ-Me and main workflow

### PR DESCRIPTION
**Pull request by Mxrcon**
# [Suggestion] Updating READ-ME

Hey @abhi18av, I took some time to update the read-me using a template that i used to other projects, I would like to also implement a dag.png workflow image as this could be a directive for new users to the pipeline and give them a nice welcome and a quick introduction to the pipeline.

# PR content
* Read-me 

# Ending

Feel free to contact me if you have any doubt, critic or suggestion. I'm at your disposal to make any changes that you request.

Hope we have a mege!

### CODE REVIEW

**Review by abhi18av — CHANGES_REQUESTED** [review]
@Mxrcon ,

For this workflow, I think we can safely uncomment all the processes which have `//DONE` in their name and regenerate the DAG.

**Comment by Mxrcon** [comment]
> @Mxrcon ,
> 
> For this workflow, I think we can safely uncomment all the processes which have `//DONE` in their name and regenerate the DAG.

Ok, I'll try to run the complete workflow

**Comment by abhi18av** [comment]
@Mxrcon 

There's a conflict.

**Comment by Mxrcon** [comment]
@abhi18av Solved! :smile:

**Review by abhi18av — APPROVED** [review]
Thanks for the contribution - looks good to merge! 👍

**Pull request merged**
