### PR TITLE
[Maintenance] Updates following camila sao paulo uptdate

### PR DESCRIPTION
**Pull request by Mxrcon**
# [Maintenance] Updates following camila sao paulo uptdate

Following the commit `d62efe0f03faec81d7ece07973b608af988cfadd` from camila sao paulo repository, i took some time to implement those changes here, for maintenance propose. 

## PR content:
1. Makefile instead of Taskfile
2. gitihgnore update
3. generate_mock_data.sh update

## Ending

If you have any questions feel free to contatc me, I'm at your disposal to make any changes you feel necessary.

Hope we have a merge!,
Davi

### CODE REVIEW

**Comment by abhi18av** [comment]
@Mxrcon , please resolve the merge conflict :)

**Comment by Mxrcon** [comment]
I think that you last changes on this pipeline, made this pr unnecessary. Sadly, but if you want to you can close and refuse this pr. I don't think that it is necessary in the moment.

**Comment by abhi18av** [comment]
Okay, thanks for for taking the time to resolve the merge conflict and updating me about the status 😊

**Comment by Mxrcon** [comment]
No problem! That's my 2nd refused pr :rofl: :rofl:

**Pull request closed without merging**
